### ISSUE TITLE
Provider 按需检查

### ISSUE THREAD

**Issue by evanli18** [oam-dev/terraform-controller#203]
我现在遇到，我只想使用平台terrafrom的能力，但是完全不依赖provider；而且我自己的 main.tf 应该也不会用到这些信息。

**Comment by zzxwill** [comment]
了解下，那你是怎么做认证授权的？

**Comment by zzxwill** [comment]
什么时候检查，什么时候不检查？

**Comment by evanli18** [comment]
我是私有云的用户，会根据自己的服务自己开发 terraform 的 Provider，但是又不想暴露自己的任性形式，是否可以指定一种 自定义的 Provider 的 credentials 呢？
