### ISSUE TITLE
The log always outputs "unable to fetch configuration"  when it is destroyed

### ISSUE THREAD

**Issue by evanli18** [oam-dev/terraform-controller#229]
VERSION: v0.2.17

https://github.com/oam-dev/terraform-controller/blob/19693758dc8c92344fbc8e6a220fd981f46ebfdd/controllers/configuration_controller.go#L111

`
		return ctrl.Result{}, client.IgnoreNotFound(err)
`

**Comment by zzxwill** [comment]
Great suggestion! Indeed, it will report the error about three to four times. Would you like to make a PR.
