### ISSUE TITLE
Map type object are not getting read by terraform controller 

### ISSUE THREAD

**Issue by bhismnarayan** [oam-dev/terraform-controller#233]
The map type object are not getting read into into terraform variable  .It always complains that the variable being read into always comes empty.
The file doesn't define case for handling map type object.
https://github.com/oam-dev/terraform-controller/blob/master/controllers/configuration/convert.go

**Comment by zzxwill** [comment]
@bhismnarayan Thanks for reporting the problem. Can you show me your Configuration?

Indeed, for map(object) type, Terraform Controller isn't fully supported, just one layer of map is supported one the one hand. I need to convert Yaml types, to Go types, and finally to Terraform types. On the other hand, I think it's very difficult for users to set complicated map in Terraform module/resource or in Configuration properties.

**Comment by bhismnarayan** [comment]
Yes,I understand that.I see that you always return key,value and value is always of type string .So,may we could just create a configmap and load that instead of environment variables
This is  application kind which gets consumed 
```

          vcn:
          - cidr: ["192.168.0.0/16"]
            name: "vcn1"
          - cidr: ["10.10.0.0/16"]
            name: "vcn1"
```
Here is the component definition 
```
variable "vcn" {        
          type= list(object({
           name=string
           cidr=list(string)
         }))        
        }
resource "oci_core_vcn" "vcn" {        
        for_each= var.vcn
        compartment_id = oci_identity_compartment.test_compartment.id
        display_name               = each.value.name
        cidr_blocks           =  each.value.cidr    
        }
```

**Comment by zzxwill** [comment]
@bhismnarayan Thanks for the post, let me verify it.

Your suggestion makes sense!

The reason why I expos the output as key-value list, is to help the application consumes the resource through environment variables from secret. https://kubevela.io/docs/next/end-user/components/cloud-services/provider-and-consume-cloud-services#bind-cloud-resources.

Most of the time, passwords are generated, so I choose secret instead of ConfigMap by default.
I would be pleased to also generate ConfigMap for it. Can you show an example of how you use the ConfigMap in an Application?

I 'd like to make a proposal based on the information you provided, and implement it later:)

**Comment by bhismnarayan** [comment]
> @bhismnarayan Thanks for the post, let me verify it.
> 
> Your suggestion makes sense!
> 
> The reason why I expos the output as key-value list, is to help the application consumes the resource through environment variables from secret. https://kubevela.io/docs/next/end-user/components/cloud-services/provider-and-consume-cloud-services#bind-cloud-resources.
> 
> Most of the time, passwords are generated, so I choose secret instead of ConfigMap by default. I would be pleased to also generate ConfigMap for it. Can you show an example of how you use the ConfigMap in an Application?
> 
> I 'd like to make a proposal based on the information you provided, and implement it later:)

**Comment by bhismnarayan** [comment]
I was thinking on reading value as object instead of reading it as string everytime  and then create configmap object and mount it as envFrom in pod.What is your opinion on this?

**Comment by zzxwill** [comment]
@bhismnarayan Yes, we support objects, besides int/string as input. And @evanli18 is enhancing the input types #236. As for outputs, they are generated as Secret and used in Pod by envFrom. 

If I am understood correctly, you want to store object/map in outputs, right?
