### ISSUE TITLE
Image size is too big 

### ISSUE THREAD

**Issue by wanfuuyu** [oam-dev/terraform-controller#303]
I consider it a great idea to build image in golang-alpine  and  packaged in alpine

```Dockerfile
FROM golang:1.17 as builder
...
FROM golang:1.17
```

to

```Dockerfile
FROM golang:1.17-alpine as builder
...
FROM alpine
```

It can reduce images size from 1G+ to less than 200MB

**Comment by wonderflow** [comment]
@wanfuuyu Great idea! Would you like to send a PR for that?
