### ISSUE TITLE
 cannot list resource "jobs"

### ISSUE THREAD

**Issue by lxd5866** [oam-dev/terraform-controller#36]
E0608 03:34:11.496995       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:default:default" cannot list resource "jobs" in API group "batch" at the cluster scop

**Comment by emanuelr93** [comment]
Same issue for me @zzxwill during a fresh installation. Maybe we need to fix some permission on serviceaccount

**Comment by zzxwill** [comment]
Got it, let me check the RBAC manifests in the chart.

**Comment by zzxwill** [comment]
The new chart is released https://github.com/oam-dev/terraform-controller/releases/tag/v0.1.9. Feel free to close this issue if you hit any issues. Thanks.
