### ISSUE TITLE
Do you want to wait 10 seconds？

### ISSUE THREAD

**Issue by lxd5866** [oam-dev/terraform-controller#38]
https://github.com/oam-dev/terraform-controller/blob/f03e9e9840df60c776e7178c041ad3804f7839a9/controllers/configuration_controller.go#L112

**Comment by zzxwill** [comment]
Thanks for asking. What's your suggestion?

**Comment by lxd5866** [comment]
I made a mistake when I was using it，I forgot to deploy providers.

**Comment by lxd5866** [comment]
I mean is `return  ctrl.Result{RequeueAfter: time.Second * 10 } , nil`

**Comment by zzxwill** [comment]
@lxd5866 You are correct. It's being fixed in #35
