### ISSUE TITLE
dev_providerconfigs not find

### ISSUE THREAD

**Issue by lxd5866** [oam-dev/terraform-controller#4]
in config/crd/kustomization.yaml
use

  ```
   resources:
  - bases/terraform.core.oam.dev_configurations.yaml
  - bases/terraform.core.oam.dev_providerconfigs.yaml
```

the  bases/terraform.core.oam.dev_providerconfigs.yaml not find in bases/

**Comment by zzxwill** [comment]
@lxd5866 Thanks for reporting this issue. 

My bad, I changed `bases/terraform.core.oam.dev_providerconfigs.yaml` to `bases/terraform.core.oam.dev_providers.yaml`, but I didn't update `config/crd/kustomization.yaml`. Fix in https://github.com/oam-dev/terraform-controller/pull/6

As the standard name for Terraform HCL/JSON files is `Configuration`, I changed `ProviderConfig` to `Provider`.
