### ISSUE TITLE
Missing permissions in tf-controller-role

### ISSUE THREAD

**Issue by lewis-od** [oam-dev/terraform-controller#42]
When following the GCP example, after applying the demo GCS bucket configuration, nothing happens.

The logs of `terraform-controller` show the following:
```
pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to watch *v1.Job: unknown (get jobs.batch)

pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:default:default" cannot list resource "configmaps" in API group "" at the cluster scope
```
It seems the `tf-controller-role` is missing permissions to list configmaps?

I'm running version 0.1.9 of `terraform-controller`

**Comment by zzxwill** [comment]
Thanks for reporting this issue and the PR.
