### ISSUE TITLE
Import hcl instead of inlining 

### ISSUE THREAD

**Issue by jmatsushita** [oam-dev/terraform-controller#46]
Hello,

I see there is a `examples/tf-native` folder with `*.tf` files. Is it possible to use external `*.tf` files instead of using `spec.hcl` yaml blocks?

Thanks!

Jun

**Comment by jmatsushita** [comment]
Also curious about pointing to a root folder containing `*.tf` files.

**Comment by jmatsushita** [comment]
The use case would be to allow operators to `terraform apply` from an admin workstation for iterative deployments before committing to a IaC repo.

**Comment by zzxwill** [comment]
@jmatsushita `examples/tf-native` folder stores those Terraform native `.hcl` and `.json` configuration files which are the source of those .yaml blocks. They can help quickly validate the configuration and help continuously maintain the Configuration .yaml files.

As this controller will be deployed to a Kubernetes controller, pointing to a root folder won't be possible unless we find a way to mounting them to the container, in which the controller run.

But we definitely can support a Github repo or folder URL, or a shared object storage URL, like OSS. Then we can have an alternative to inlining Terraform configurations. Does it match your requirement?

**Comment by roberthstrand** [comment]
I'm looking through some of the projects related to running Terraform with an Operator or Controller method, and personally it really detracts to the experience if I cannot use a git repository to store `.hcl` files and have it be picked up by the controller as the source.

**Comment by zzxwill** [comment]
@roberthstrand Thanks for your feedback. The remote HCL git repo support will be implemented soon. Thanks.

**Comment by Belyenochi** [comment]
I would like apply for this project under the LFX mentorship program. I have read the previous comments and the requirements you mentioned. Looking forward to it. :)

**Comment by zzxwill** [comment]
@Belyenochi Looking forward to your contribution:)

**Comment by zzxwill** [comment]
@jmatsushita @roberthstrand , it's supported in #110 .

**Comment by roberthstrand** [comment]
Excellent, thank you for the update. I will give it a spin this weekend.

**Comment by zzxwill** [comment]
Based on this feature,  sub-folders of a git repo to indicate the HCL file location will be supported #124 .
