### ISSUE TITLE
Question: What's the benefits for introducing terraform kubernetes controller ?

### ISSUE THREAD

**Issue by Colstuwjx** [oam-dev/terraform-controller#47]
Hi team,

It's absolutely a great project, and It will be appreciated if we could setup some documents about:

* What's the difference between terraform controller and crossplane;
* How could we get benefits from introducing terraform controller, e.g. it's just integrate terraform with k8s, or they would produce a chemical reaction.

Thanks!

**Comment by zzxwill** [comment]
@Colstuwjx Those two are very good questions.

> What's the difference between Terraform controller and Crossplane

Terraform controller and Crossplane providers are both services for cloud resource provisioning. They differ in
- To support one cloud resource, like Alibaba cloud RDS database, Terraform controller just needs to explore the right Terraform modules, and support it based on the module or configuration file. Crossplane needs to write CRUD code for the resource in provider-alibaba.
- Terraform controller can use nearly all Terraform configurations (HCl/JSON) across AWS/Azure/AlibabaCloud/GCP and more other cloud providers. This means it can provision much more cloud resources based on those Terraform configurations which are mature and robust enough. But for Crossplane, one needs to depend on provider-aws, provider-gcp, provider-alibaba, and provider-xxx to reach the goal.
- To provision a cloud resource, Terraform controller works like a job, while Crossplane works as a reconciler to check and execute the resource.

Basides the differences, Crossplane provider a super cool way to accept credentials from cloud providers `ProviderConfig`, [Terraform configuration learnt from it](https://github.com/oam-dev/terraform-controller/blob/master/DESIGN.md#provider).

> How could we get benefits from introducing terraform controller, e.g. it's just integrate terraform with k8s, or they would produce a chemical reaction.

By introduction Terraform controller, we provide a Kubernetes way to provision cloud resources and we populate the output connection (like RDS url/port/username/password) in a secret, which can be easily consumed by business applications. You can find some examples of cloud resource consumption [here](https://kubevela.io/docs/end-user/components/cloud-services).
