### ISSUE TITLE
Configuration object does not reflect error during provisioning

### ISSUE THREAD

**Issue by Madhur97** [oam-dev/terraform-controller#88]
While running the example present in [Getting Started](https://github.com/oam-dev/terraform-controller/blob/master/getting-started.md) guide for AWS, it was observed that if there is any error (e.g. invalid region/credentials) in the _aws-s3-apply_ job,  the status in configuration object remains `Provisioning` indefinitely.
On running `kubectl describe configuration.terraform.core.oam.dev aws-s3`  we get 
```
Status:
  Message:  Cloud resources are being provisioned.
  State:      Provisioning
Events:       <none>
``` 
Ideally, the status of configuration object should reflect that there is some error during the job. 

Release version - v0.1.13
Cloud - AWS

**Comment by zzxwill** [comment]
Fixed in #98. Feel feel to reopen this issue if the feature doesn't meet your expectation:)
